version: '3'

services:
  analytics_db:
      image: postgres
      container_name: meltano_analytics_postgres
      volumes:
        - /Users/david/var/postgresql:/var/lib/postgresql
      ports:
        - "5439:5432"
      expose:
        - 5439
      networks:
        - meltano
      environment:
        POSTGRES_USER: pguser
        POSTGRES_PASSWORD: pguser
        POSTGRES_DB: pgdb
  google_play_api:
      container_name: google_play_api
      build:
        context: .
        dockerfile: ./google-play-api/Dockerfile
      ports:
        - "80:3000"
      expose:
        - 80
      networks:
        - meltano
  metabase:
    container_name: metabase
    image: metabase/metabase
    ports:
        - "8000:3000"
    expose:
        - 8000
    networks:
        - meltano
  meltano-ui:
    container_name: meltano_ui
    build:
        context: ./meltano
    command: ui
    environment:
      MELTANO_DATABASE_URI: postgresql://postgres:postgres@meltano-system-db/meltano
      MELTANO_SEND_ANONYMOUS_USAGE_STATS: "false"
      MELTANO_DISABLE_TRACKING: "false"
      MELTANO_PROJECT_READONLY: "false"
    volumes:
      - ./meltano:/project
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - meltano-system-db
      - google_play_api
    networks:
      - meltano
    restart: unless-stopped
  meltano-system-db:
    image: postgres
    container_name: meltano_system_postgres
    environment:
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: meltano
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - meltano_postgresql_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - meltano
    restart: unless-stopped

networks:
  meltano:
    driver: bridge


volumes:
  meltano_postgresql_data:
    driver: local
  meltano_elt_logs_data:
    driver: local
